name: Update Upstream

on:
    # Monthly
    schedule:
      - cron: '0 0 * * *'
    # Manual trigger
    workflow_dispatch:
      inputs:

jobs:
    update-kohi-den:
        name: Update Kohi-den
        runs-on: ubuntu-latest

        steps:
          - name: Set env
            run: |
                echo "UPSTREAM_URL=https://github.com/Kohi-den/extensions-source.git" >> $GITHUB_ENV
                echo "UPSTREAM_BRANCH=main" >> $GITHUB_ENV
                echo "LOCAL_BRANCH=kohiden" >> $GITHUB_ENV

          - name: Checkout repository
            uses: actions/checkout@v4
            with:
                ref: ${{env.LOCAL_BRANCH}}
                token: ${{ secrets.BOT_PAT }}

          - name: Add remote repository
            run: git remote add upstream ${{env.UPSTREAM_URL}}

          - name: Fetch upstream changes
            run: git fetch upstream

          - name: Merge upstream changes
            run: git merge upstream/${{env.UPSTREAM_BRANCH}}

          - name: Push changes to repository
            run: git push origin ${{env.LOCAL_BRANCH}}

    update-dark25:
        name: Update Dark25
        runs-on: ubuntu-latest

        steps:
          - name: Set env
            run: |
                echo "UPSTREAM_URL=https://github.com/Dark25/aniyomi-extensions.git" >> $GITHUB_ENV
                echo "UPSTREAM_BRANCH=master" >> $GITHUB_ENV
                echo "LOCAL_BRANCH=dark25" >> $GITHUB_ENV

          - name: Checkout repository
            uses: actions/checkout@v4
            with:
                ref: ${{env.LOCAL_BRANCH}}
                token: ${{ secrets.BOT_PAT }}

          - name: Add remote repository
            run: git remote add upstream ${{env.UPSTREAM_URL}}

          - name: Fetch upstream changes
            run: git fetch upstream

          - name: Merge upstream changes
            run: git merge upstream/${{env.UPSTREAM_BRANCH}}

          - name: Push changes to repository
            run: git push origin ${{env.LOCAL_BRANCH}}